import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col bg-background text-foreground`}
      >
        <Providers>
          {/* Navbar - full width with inner container */}
          <header className="w-full">
            <div className="max-w-7xl mx-auto px-4">
              <Navbar />
            </div>
          </header>

          {/* Main content - centered container */}
          <main className="flex-1 w-full">
            <div className="max-w-7xl mx-auto px-4">{children}</div>
          </main>

          {/* Footer - full width with inner container */}
          <footer className="w-full">
            <div className="max-w-7xl mx-auto px-4">
              <Footer />
            </div>
          </footer>
        </Providers>
      </body>
    </html>
  );
}
