import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Lisa Hospital",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col bg-background text-foreground dark:bg-gray-900`}
      >
        <Providers>
          {/* Global container for all page content except footer */}
          <div className="flex-1 w-full max-w-7xl mx-auto px-4 flex flex-col">
            <header>
              <Navbar />
            </header>

            <main className="flex-1">{children}</main>
          </div>

          {/* Footer with full-width background */}
          <footer className="w-full bg-gray-900 text-white">
            <div className="max-w-7xl mx-auto px-4 mt-10">
              <Footer />
            </div>
          </footer>
        </Providers>
      </body>
    </html>
  );
}